AWSTemplateFormatVersion: 2010-09-09

Description: 
  This is the DE SBD Predict Windows instance

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Select the key pair for Windows instance password decryption
  VPC:
    Type: AWS::EC2::VPC::Id
    Description: Select the VPC ID created in the previous template
  Subnet:
    Type: AWS::EC2::Subnet::Id
    Description: Select the public subnet ID created in the previous template
  SecurityGroupIds:
    Type: List<AWS::EC2::SecurityGroup::Id>
    Description: Select the security group(s) ID created in the previous template
  LatestWindowsAmiId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Description: Specify the latest Windows AMI ID
    Default: /aws/service/ami-windows-latest/Windows_Server-2019-English-Full-Base

Resources:
  WindowsInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: WindowsInstanceRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      

  WindowsInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref WindowsInstanceRole

  WindowsInstanceRolePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub "Windows-client-${AWS::StackName}"
      Roles:
        - !Ref WindowsInstanceRole
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - s3:Get*
              - s3:List*
            Resource: "*"
      
      
  WindowsInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LatestWindowsAmiId
      KeyName: !Ref KeyName
      InstanceType: t2.micro
      SecurityGroupIds: !Ref SecurityGroupIds
      SubnetId: !Ref Subnet
      IamInstanceProfile: !Ref WindowsInstanceProfile
      Tags:
        - Key: Name
          Value: DE-Extract-Windows-Instance

